#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="/etc/penpot/penpot.env"

required_vars=(
  PENPOT_PUBLIC_URI
  PENPOT_SECRET_KEY
)

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "missing required variable: ${var_name}" >&2
    exit 1
  fi
done

cat > "${ENV_FILE}" <<EOF
PENPOT_VERSION="${PENPOT_VERSION:-latest}"
PENPOT_PUBLIC_URI="${PENPOT_PUBLIC_URI}"
PENPOT_SECRET_KEY="${PENPOT_SECRET_KEY}"
PENPOT_FLAGS="${PENPOT_FLAGS:-enable-prepl-server}"
PENPOT_HTTP_SERVER_MAX_BODY_SIZE="${PENPOT_HTTP_SERVER_MAX_BODY_SIZE:-367001600}"
PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE="${PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE:-367001600}"
PENPOT_TELEMETRY_ENABLED="${PENPOT_TELEMETRY_ENABLED:-true}"
PENPOT_TELEMETRY_REFERER="${PENPOT_TELEMETRY_REFERER:-aws}"
PENPOT_DATABASE_URI="${PENPOT_DATABASE_URI:-postgresql://penpot-postgres/penpot}"
PENPOT_DATABASE_USERNAME="${PENPOT_DATABASE_USERNAME:-penpot}"
PENPOT_DATABASE_PASSWORD="${PENPOT_DATABASE_PASSWORD:-penpot}"
PENPOT_REDIS_URI="${PENPOT_REDIS_URI:-redis://penpot-valkey/0}"
PENPOT_OBJECTS_STORAGE_BACKEND="${PENPOT_OBJECTS_STORAGE_BACKEND:-fs}"
PENPOT_OBJECTS_STORAGE_FS_DIRECTORY="${PENPOT_OBJECTS_STORAGE_FS_DIRECTORY:-/opt/data/assets}"
PENPOT_SMTP_DEFAULT_FROM="${PENPOT_SMTP_DEFAULT_FROM:-no-reply@example.com}"
PENPOT_SMTP_DEFAULT_REPLY_TO="${PENPOT_SMTP_DEFAULT_REPLY_TO:-no-reply@example.com}"
PENPOT_SMTP_HOST="${PENPOT_SMTP_HOST:-}"
PENPOT_SMTP_PORT="${PENPOT_SMTP_PORT:-587}"
PENPOT_SMTP_USERNAME="${PENPOT_SMTP_USERNAME:-}"
PENPOT_SMTP_PASSWORD="${PENPOT_SMTP_PASSWORD:-}"
PENPOT_SMTP_TLS="${PENPOT_SMTP_TLS:-true}"
PENPOT_SMTP_SSL="${PENPOT_SMTP_SSL:-false}"
EOF

chmod 0600 "${ENV_FILE}"
echo "Penpot environment written to ${ENV_FILE}"
