#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="/etc/penpot/penpot.env"

required_vars=(
  PENPOT_VERSION
  PENPOT_PUBLIC_URI
  PENPOT_SECRET_KEY
)

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "missing required variable: ${var_name}" >&2
    exit 1
  fi
done

PENPOT_DATABASE_MODE="${PENPOT_DATABASE_MODE:-local}"
PENPOT_VALKEY_MODE="${PENPOT_VALKEY_MODE:-local}"
COMPOSE_PROFILE_LIST=()

case "${PENPOT_DATABASE_MODE}" in
  local)
    PENPOT_DATABASE_HOST="${PENPOT_DATABASE_HOST:-penpot-postgres}"
    PENPOT_DATABASE_PORT="${PENPOT_DATABASE_PORT:-5432}"
    PENPOT_DATABASE_NAME="${PENPOT_DATABASE_NAME:-penpot}"
    PENPOT_DATABASE_USERNAME="${PENPOT_DATABASE_USERNAME:-penpot}"
    PENPOT_DATABASE_PASSWORD="${PENPOT_DATABASE_PASSWORD:-penpot}"
    PENPOT_DATABASE_URI="${PENPOT_DATABASE_URI:-postgresql://${PENPOT_DATABASE_HOST}:${PENPOT_DATABASE_PORT}/${PENPOT_DATABASE_NAME}}"
    COMPOSE_PROFILE_LIST+=(local-postgres)
    ;;
  external)
    external_required_vars=(
      PENPOT_DATABASE_HOST
      PENPOT_DATABASE_PORT
      PENPOT_DATABASE_NAME
      PENPOT_DATABASE_USERNAME
      PENPOT_DATABASE_PASSWORD
    )

    for var_name in "${external_required_vars[@]}"; do
      if [[ -z "${!var_name:-}" ]]; then
        echo "missing required variable for external database mode: ${var_name}" >&2
        exit 1
      fi
    done

    PENPOT_DATABASE_URI="${PENPOT_DATABASE_URI:-postgresql://${PENPOT_DATABASE_HOST}:${PENPOT_DATABASE_PORT}/${PENPOT_DATABASE_NAME}}"
    ;;
  *)
    echo "unsupported PENPOT_DATABASE_MODE: ${PENPOT_DATABASE_MODE}" >&2
    exit 1
    ;;
esac

case "${PENPOT_VALKEY_MODE}" in
  local)
    PENPOT_REDIS_URI="${PENPOT_REDIS_URI:-redis://penpot-valkey/0}"
    COMPOSE_PROFILE_LIST+=(local-valkey)
    ;;
  external)
    if [[ -z "${PENPOT_REDIS_URI:-}" ]]; then
      echo "missing required variable for external Valkey mode: PENPOT_REDIS_URI" >&2
      exit 1
    fi
    ;;
  *)
    echo "unsupported PENPOT_VALKEY_MODE: ${PENPOT_VALKEY_MODE}" >&2
    exit 1
    ;;
esac

COMPOSE_PROFILES="$(IFS=,; echo "${COMPOSE_PROFILE_LIST[*]}")"

cat > "${ENV_FILE}" <<EOF
PENPOT_VERSION="${PENPOT_VERSION}"
PENPOT_PUBLIC_URI="${PENPOT_PUBLIC_URI}"
PENPOT_SECRET_KEY="${PENPOT_SECRET_KEY}"
PENPOT_DATABASE_MODE="${PENPOT_DATABASE_MODE}"
PENPOT_FLAGS="${PENPOT_FLAGS:-enable-prepl-server}"
PENPOT_VALKEY_MODE="${PENPOT_VALKEY_MODE}"
PENPOT_HTTP_SERVER_MAX_BODY_SIZE="${PENPOT_HTTP_SERVER_MAX_BODY_SIZE:-367001600}"
PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE="${PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE:-367001600}"
PENPOT_TELEMETRY_ENABLED="${PENPOT_TELEMETRY_ENABLED:-true}"
PENPOT_TELEMETRY_REFERER="${PENPOT_TELEMETRY_REFERER:-aws}"
PENPOT_DATABASE_URI="${PENPOT_DATABASE_URI}"
PENPOT_DATABASE_HOST="${PENPOT_DATABASE_HOST}"
PENPOT_DATABASE_PORT="${PENPOT_DATABASE_PORT}"
PENPOT_DATABASE_NAME="${PENPOT_DATABASE_NAME}"
PENPOT_DATABASE_USERNAME="${PENPOT_DATABASE_USERNAME}"
PENPOT_DATABASE_PASSWORD="${PENPOT_DATABASE_PASSWORD}"
PENPOT_REDIS_URI="${PENPOT_REDIS_URI}"
COMPOSE_PROFILES="${COMPOSE_PROFILES}"
PENPOT_OBJECTS_STORAGE_BACKEND="${PENPOT_OBJECTS_STORAGE_BACKEND:-fs}"
PENPOT_OBJECTS_STORAGE_FS_DIRECTORY="${PENPOT_OBJECTS_STORAGE_FS_DIRECTORY:-/opt/data/assets}"
PENPOT_SMTP_DEFAULT_FROM="${PENPOT_SMTP_DEFAULT_FROM:-no-reply@example.com}"
PENPOT_SMTP_DEFAULT_REPLY_TO="${PENPOT_SMTP_DEFAULT_REPLY_TO:-no-reply@example.com}"
PENPOT_SMTP_HOST="${PENPOT_SMTP_HOST:-}"
PENPOT_SMTP_PORT="${PENPOT_SMTP_PORT:-587}"
PENPOT_SMTP_USERNAME="${PENPOT_SMTP_USERNAME:-}"
PENPOT_SMTP_PASSWORD="${PENPOT_SMTP_PASSWORD:-}"
PENPOT_SMTP_TLS="${PENPOT_SMTP_TLS:-true}"
PENPOT_SMTP_SSL="${PENPOT_SMTP_SSL:-false}"
EOF

chmod 0600 "${ENV_FILE}"
echo "Penpot environment written to ${ENV_FILE}"
